import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Board from './board/board'
import SocketLogic from './board/socketLogic'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <SocketLogic />
            {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
        </div>
    )
}
